import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google"; // Corrected import path
import "./globals.css";
//import {Header} from "./component/Header";


// Google Fonts configuration
const inter = Inter({
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${inter.className}`} // Added correct font classes
      >
        {children}
      </body>
    </html>
  );
}
